<template>
  <!-- Wrapper start -->
  <div id="wrapper" class="wrap overflow-hidden-x">
    <div
      class="breadcrumbs panel z-1 py-2 bg-gray-25 dark:bg-gray-100 dark:bg-opacity-5 dark:text-white"
    >
      <div class="container max-w-xl">
        <ul class="breadcrumb nav-x justify-center gap-1 fs-7 sm:fs-6 m-0">
          <li><a href="index.html">Home</a></li>
          <li><i class="unicon-chevron-right opacity-50"></i></li>
          <li><span class="opacity-50">Privacy policy</span></li>
        </ul>
      </div>
    </div>

    <div class="section py-4 lg:py-6 xl:py-8">
      <div class="container max-w-lg">
        <div class="page-wrap panel vstack gap-4 lg:gap-6 xl:gap-8">
          <header
            class="page-header panel vstack justify-center gap-2 lg:gap-4 text-center"
          >
            <div class="panel">
              <h1 class="h3 lg:h1 m-0">Privacy policy</h1>
            </div>
          </header>
          <div class="page-content panel fs-6 md:fs-5">
            <h2><b>Interpretation and Definitions</b></h2>

            <br />

            <h3><b>Interpretation</b></h3>

            <p>
              The words of which the initial letter is capitalized have meanings
              defined under the following conditions. The following definitions
              shall have the same meaning regardless of whether they appear in
              singular or in plural.
            </p>

            <br />

            <h3><b>Definitions</b></h3>

            <ul class="list list-bullets">
              <li>
                <b>Account</b> means a unique account created for You to access
                our Service or parts of our Service.
              </li>
              <li>
                <b>Affiliate</b> means an entity that controls, is controlled by
                or is under common control with a party, where "control" means
                ownership of 50% or more of the shares, equity interest or other
                securities entitled to vote for election of directors or other
                managing authority.
              </li>
              <li>
                <b>Company</b> (referred to as either "the Company", "We", "Us"
                or "Our" in this Agreement) refers to Daily Times.
              </li>
              <li>
                <b>Cookies</b> are small files that are placed on Your computer,
                mobile device or any other device by a website, containing the
                details of Your browsing history on that website among its many
                uses.
              </li>
              <li><b>Country</b> refers to: Gujarat, India</li>
              <li>
                <b>Device</b> means any device that can access the Service such
                as a computer, a cellphone or a digital tablet.
              </li>
              <li>
                <b>Personal Data</b> is any information that relates to an
                identified or identifiable individual.
              </li>
              <li>
                <b>Usage Data</b> refers to data collected automatically, either
                generated by the use of the Service or from the Service
                infrastructure itself (for example, the duration of a page
                visit).
              </li>
            </ul>

            <h2><b>Retention of Your Personal Data</b></h2>

            <p>
              The Company will retain Your Personal Data only for as long as is
              necessary for the purposes set out in this Privacy Policy. We will
              retain and use Your Personal Data to the extent necessary to
              comply with our legal obligations (for example, if we are required
              to retain your data to comply with applicable laws), resolve
              disputes, and enforce our legal agreements and policies.
            </p>

            <p>
              The Company will also retain Usage Data for internal analysis
              purposes. Usage Data is generally retained for a shorter period of
              time, except when this data is used to strengthen the security or
              to improve the functionality of Our Service, or We are legally
              obligated to retain this data for longer time periods.
            </p>

            <br />

            <h2><b>Transfer of Your Personal Data</b></h2>

            <p>
              Your information, including Personal Data, is processed at the
              Company's operating offices and in any other places where the
              parties involved in the processing are located. It means that this
              information may be transferred to — and maintained on — computers
              located outside of Your state, province, country or other
              governmental jurisdiction where the data protection laws may
              differ than those from Your jurisdiction.
            </p>

            <p>
              Your consent to this Privacy Policy followed by Your submission of
              such information represents Your agreement to that transfer.
            </p>

            <p>
              The Company will take all steps reasonably necessary to ensure
              that Your data is treated securely and in accordance with this
              Privacy Policy and no transfer of Your Personal Data will take
              place to an organization or a country unless there are adequate
              controls in place including the security of Your data and other
              personal information.
            </p>

            <br />

            <h2><b>Delete Your Personal Data</b></h2>

            <p>
              You have the right to delete or request that We assist in deleting
              the Personal Data that We have collected about You.
            </p>

            <p>
              Our Service may give You the ability to delete certain information
              about You from within the Service.
            </p>

            <p>
              You may update, amend, or delete Your information at any time by
              signing in to Your Account, if you have one, and visiting the
              account settings section that allows you to manage Your personal
              information. You may also contact Us to request access to,
              correct, or delete any personal information that You have provided
              to Us.
            </p>

            <p>
              Please note, however, that We may need to retain certain
              information when we have a legal obligation or lawful basis to do
              so.
            </p>
          </div>
          <div class="page-footer panel">
            <p class="fs-7 opacity-60 m-0">Last updated: 27 Oct, 2024</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Wrapper end -->
</template>
